/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rzamboni' at '07/10/16 14:49' with Gradle 3.1
 *
 * @author rzamboni, @date 07/10/16 14:49
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
